[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "neural_test"
version = "0.1.0"
description = "Test neural network for xor"
dependencies = ["numpy", "matplotlib"]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "GPLv3"}
